backend:
  name: test-repo
  git: https://github.com/greenlightjohnny/project3

media_folder: static/assets
public_folder: assets

collections:
  - label: "Pages"
    name: "pages"

    files:
      - label: "About Page"
        name: "about"
        file: "content/blog/landingpage/middle.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Position, name: position, widget: string }
              - { label: Photo, name: photo, widget: image }
