backend:
  name: github
  repo: greenlightjohnny/project3

media_folder: static/assets
public_folder: assets

collections:
  - label: "Main Page"
    name: "Main Page"

    files:
      - label: "Section One"
        name: "Section One"
        file: "content/pages/main/sectionone.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }

      - label: "Section Two"
        name: "Section Two"
        file: "content/pages/main/sectiontwo.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }

      - label: "Section Three"
        name: "Section Three"
        file: "content/pages/main/sectionthree.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
