backend:
  name: git-gateway
  repo: greenlightjohnny/project3

media_folder: static/assets
public_folder: assets

collections:
  - label: "Main Page"
    name: "Main Page"

    files:
      - label: "Section One"
        name: "Section One"
        file: "content/pages/main/section1.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Date, name: date, widget: datetime }

      - label: "Section Two"
        name: "Section Two"
        file: "content/pages/main/section2.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Date, name: date, widget: datetime }

      - label: "Section Three"
        name: "Section Three"
        file: "content/pages/main/section3.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Date, name: date, widget: datetime }

  - label: "Basics Page"
    name: "Basics Page"

    files:
      - label: "Section One"
        name: "Section One"
        file: "content/pages/basics/basics1.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Date, name: date, widget: datetime }

      - label: "Section Two"
        name: "Section Two"
        file: "content/pages/basics/basics2.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Date, name: date, widget: datetime }

  - label: "Traditional Page"
    name: "Traditional Page"

    files:
      - label: "Section One"
        name: "Section One"
        file: "content/pages/traditional/traditional1.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Date, name: date, widget: datetime }

      - label: "Section Two"
        name: "Section Two"
        file: "content/pages/traditional/traditional2.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Date, name: date, widget: datetime }

      - label: "Section Three"
        name: "Section Three"
        file: "content/pages/traditional/traditional3.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Date, name: date, widget: datetime }

      - label: "Section Four"
        name: "Section Four"
        file: "content/pages/traditional/traditional4.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Date, name: date, widget: datetime }

  - label: "Alternative Page"
    name: "Alternative Page"

    files:
      - label: "Section One"
        name: "Section One"
        file: "content/pages/alternative/alternative1.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Date, name: date, widget: datetime }

      - label: "Section Two"
        name: "Section Two"
        file: "content/pages/alternative/alternative2.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Date, name: date, widget: datetime }

      - label: "Section Three"
        name: "Section Three"
        file: "content/pages/alternative/alternative3.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Date, name: date, widget: datetime }

      - label: "Section Four"
        name: "Section Four"
        file: "content/pages/alternative/alternative4.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Date, name: date, widget: datetime }

  - label: "About Page"
    name: "About Page"

    files:
      - label: "Section One"
        name: "Section One"
        file: "content/pages/about/about1.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Date, name: date, widget: datetime }

      - label: "Section Two"
        name: "Section Two"
        file: "content/pages/about/about2.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Date, name: date, widget: datetime }

      - label: "Section Three"
        name: "Section Three"
        file: "content/pages/about/about3.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Date, name: date, widget: datetime }

      - label: "Section Four"
        name: "Section Four"
        file: "content/pages/about/about4.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Date, name: date, widget: datetime }
