backend:
  name: test-repo

media_folder: static/blog
public_folder: assets/blog

collections:
  - label: "Pages"
    name: "pages"

    files:
      - label: "About Page"
        name: "about"
        file: "landingpage/top.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Position, name: position, widget: string }
              - { label: Photo, name: photo, widget: image }
