backend:
  name: github
  repo: greenlightjohnny/project3

media_folder: static/assets
public_folder: assets

collections:
  - label: "Main Page"
    name: "Main Page"

    files:
      - label: "Section One"
        name: "Section One"
        file: "content/pages/main/section1.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Date, name: date, widget: datetime }

      - label: "Section Two"
        name: "Section Two"
        file: "content/pages/main/section2.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Date, name: date, widget: datetime }

      - label: "Section Three"
        name: "Section Three"
        file: "content/pages/main/section3.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Date, name: date, widget: datetime }
